### ISSUE TITLE
MultiColumnComboBox shows an empty container that is visible when opening and closing the list.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1069]
MultiColumnComboBox shows an empty container that is visible when opening and closing the list.

This can be seen in this demo when we open and close MultiColumnComboBox:

https://stackblitz.com/edit/react-f9tz8b?file=index.html

**Comment by nstoychev** [comment]
Setting the following style resolves the issue:
```css
div.k-dropdowngrid-popup {
    background-color: transparent;
}
```
