### ISSUE TITLE
Dropdowns animation

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-react#1181]
The animation container changes its position if you hover an item in the popup while the open animation plays.

Example: https://stackblitz.com/edit/react-7a7qjc?file=index.html

Workaround:
```css
.k-animation-container:not(.k-animation-container-shown) li.k-list-item:hover {
   background-color: inherit;
}
```
