### ISSUE TITLE
[Enhancement][PfViewer] Add support for different font-weights

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#2084]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
Currently, font weights from 500 to 900 are all treated as bold. Intermediate values are ignored regardless of the registered fonts.

Internal Item: https://github.com/telerik/kendo-drawing/issues/281

We should allow registering one variant for each standard font weight, e.g.

````css
@font-face {
  font-family: Raleway;
  src: url("./Raleway/Raleway-Regular.ttf") format("truetype");
  font-weight: normal;
  font-style: normal;
}
@font-face {
  font-family: "Raleway";
  src: url("./Raleway/Raleway-Medium.ttf") format("truetype");
  font-weight: 500;
  font-style: normal;
}
@font-face {
  font-family: "Raleway";
  src: url("./Raleway/Raleway-SemiBold.ttf") format("truetype");
  font-weight: 600;
  font-style: normal;
}
@font-face {
  font-family: "Raleway";
  src: url("./Raleway/Raleway-Bold.ttf") format("truetype");
  font-weight: bold;
  font-style: normal;
}
````
These will show up correctly in the browser:
![image](https://github.com/telerik/kendo-react/assets/6196386/f3b176e7-dacb-4d71-ae86-2eff3b242932)
﻿﻿
But will be binned as bold and regular in the PDF:
![image](https://github.com/telerik/kendo-react/assets/6196386/a3aaf0b9-ea32-4cab-829c-7c20c05e8fb0)
