### ISSUE TITLE
The Switch layout is misaligned on IE 11

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#220]
The Switch layout is misaligned on IE 11.

![image](https://user-images.githubusercontent.com/11087921/54738802-5a28bf00-4bbe-11e9-91aa-7eb104343935.png)

This is reproducible in our demos as well.

**Comment by vladimirivanoviliev** [comment]
No longer reproducible in IE11 using v.2.11.0

**Comment by mcapkovic** [comment]
Hi, 
I can reproduce this issue in latest kendo on IE11
https://stackblitz.com/edit/react-f4sowy
https://react-f4sowy.stackblitz.io/ 
https://react-hszj1f.stackblitz.io/

![switch](https://user-images.githubusercontent.com/26137370/77428405-4f5bc800-6dd8-11ea-85da-316d5af8f33d.PNG)

**Comment by silviyaboteva** [comment]
This issue is caused by the fact that in IE the property `display: -ms-inline-flexbox` expects the child element to have explicitly set width. Otherwise, the switch container loses its width and the calculation of the position becomes wrong.

The fix will be provided in the themes.

A workaround, for now, can be observed in this demo: [https://stackblitz.com/edit/react-f4sowy-xekutq?file=index.html](https://stackblitz.com/edit/react-f4sowy-xekutq?file=index.html). 
by applying the following line of CSS
``` CSS
.k-switch-container {
  /* width: 6em; for Default theme */
  /* width: 4.6em; for Material theme */
  width: 5em; /* for Bootstrap theme */
}
```
