### ISSUE TITLE
Custom Grid paging buttons

### ISSUE THREAD

**Issue by VSalashnyi** [telerik/kendo-react#264]
How to change default Grid paging arrows to the buttons "Next", "Previous"?

**Comment by Xizario** [comment]
These buttons are using Font Icons. You can place any content in the spans, with css:
```css
.k-grid-pager .k-i-arrow-e::before {
	content: 'A'
}

.k-grid-pager .k-i-arrow-w::before {
	content: 'B'
}
```

We have further plans to expose the content of the pager as components.
