### ISSUE TITLE
[Bug][Grid] Grid with scrollable set to none produces different rendering

### ISSUE THREAD

**Issue by NickIliev** [telerik/kendo-react#2890]
### Description

The rendering of a grid that has [**scrollable** set to **none*](https://www.telerik.com/kendo-react-ui/components/grid/scroll-modes#non-scrollable-mode)* is different from [the reference rendering in the source of truth tests](https://github.com/telerik/kendo-themes/blob/develop/tests/grid/grid-react-basic.html)

The issue is now reproducible with the non-scrollable grid in KendoReact + ThemeBuilder Q1 2025
reported through t.1679104

Temporary solution:

explicitly remove the following CSS classes from the generated CSS (there might be additional CSS classes that also should be removed)
```css
.k-table
.k-table-thead
```

Example CSS as generated from ThemeBuilder and as per the source of truth tests:
```CSS
    .k-grid.k-grid-md .k-table .k-table-tbody .k-master-row.k-table-row {
        background-color: purple;
        background-image: none;
        color: white;
    }

    .k-grid.k-grid-md .k-table-thead .k-table-row .k-header.k-table-th .k-cell-inner .k-link,
    .k-grid.k-grid-md .k-grid-header .k-table-row .k-header.k-table-th .k-cell-inner .k-link {
        background-color: green;
        background-image: none;
        color: yellow;
    }

    .k-grid.k-grid-md .k-table-tbody .k-master-row.k-table-row.k-selected>td {
        color: lime;
    }

    .k-grid.k-grid-md .k-grouping-header {
        background-color: var(--tb-kendo-color-success-subtle-active);
        background-image: none;
    }

    .k-grid.k-grid-md .k-table-thead .k-table-row .k-header.k-table-th.k-sorted .k-cell-inner .k-link .k-sort-icon .k-icon.k-svg-icon.k-svg-i-sort-asc-small>svg,
    .k-grid.k-grid-md .k-grid-header .k-table-row .k-header.k-table-th.k-sorted .k-cell-inner .k-link .k-sort-icon .k-icon.k-svg-icon.k-svg-i-sort-asc-small>svg {
        color: red;
    }

    .k-grid.k-grid-md .k-table-thead .k-table-row.k-filter-row,
    .k-grid.k-grid-md .k-grid-header .k-table-row.k-filter-row {
        background-color: yellow;
        background-image: none;
    }

    .k-grid.k-grid-md .k-table .k-table-group-row.k-grouping-row.k-table-row .k-reset {
        background-color: var(--tb-kendo-color-error-subtle-hover);
        background-image: none;
    }
```

### Steps To Reproduce

1. Create a grid in KendoReact with **scrollable** set to **none**
2. Test the CSS generated from ThemeBuilder that generates rendering as per the source of truth tests https://github.com/telerik/kendo-themes/blob/develop/tests/grid/grid-react-basic.html

Result: https://codesandbox.io/p/devbox/silly-swanson-j5v78x?workspaceId=ws_9xJ8sL1dDMb46o8AzCwPr7

### Actual Behavior

https://codesandbox.io/p/devbox/silly-swanson-j5v78x?workspaceId=ws_9xJ8sL1dDMb46o8AzCwPr7

### Expected Behavior

https://codesandbox.io/p/sandbox/silly-voice-6nhmm3

### Browser

Chrome

### Browser version

latest

### OS type

MacOS
