### ISSUE TITLE
Scss styling error button-size() material theme

### ISSUE THREAD

**Issue by arjenhbp** [telerik/kendo-react#352]
## I'm submitting a...
* Bug report 

## Current behavior
If you render an Grid element using scss styling from (atleast) the material theme. The paging numbers aren't rendered as circular buttons as they do when using css styling. Instead the're smushed up together.

The Chrome DevTools provides a "Invalid property value" error in the following css
```css
.k-pager-wrap .k-link, .k-pager-wrap .k-state-selected {
    padding: 0;
    width: calc( 1 * ( 0 + 16px + 1.42857em )); /* <-- Invalid property value */
    height: calc( 1 * ( 0 + 16px + 1.42857em )); /* <-- Invalid property value */
    box-sizing: border-box;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    position: relative;
    text-align: center;
    z-index: 1;
}
```

## Expected behavior
No css error should happen and the paging number should be rendered as circular buttons.

## Minimal reproduction of the problem with instructions
See fork for demo
[https://stackblitz.com/edit/react-1grq2q?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-1grq2q?file=app%2Fmain.jsx)

Comment either the scss or css import (in main.jsx) to see the difference. (reload required)

## What is the motivation or use case for changing the behavior?
No css error should happen when using scss styling and the ui should be rendered the same when using either css or scss.

## Environment

Package versions:
```
react@16.9.0
react-dom@16.9.0
react-scripts@3.0.1
node-sass@4.12.0
@progress/kendo-data-query@1.5.2
@progress/kendo-drawing@1.6.0
@progress/kendo-react-animation@3.4.1
@progress/kendo-react-dateinputs@3.4.1
@progress/kendo-react-dropdowns@3.4.1
@progress/kendo-react-grid@3.4.1
@progress/kendo-react-inputs@3.4.1
@progress/kendo-react-intl@3.4.1
@progress/kendo-theme-default@4.3.3
@progress/kendo-theme-material@3.3.4
```

Browser:
- Chrome (desktop) version: 77.0.3865.120
- Chrome (Android) version: 77.03865.92
- Edge version: 44.18362.387.0

System:
- Node version: v10.16.0
- Npm version: 6.9.0
- Platform:  Windows

## Solution
I found that the calc(...) function was used in an incorrect way in the button sizing methods.
```
./node_modules/@progress/kendo-theme-material/modules/@progress/kendo-theme-default/scss/mixins/_button-size.scss
```

Below is a solution to solve this bug. I'm not a css expert, so please improve were needed.
```
@function button-size( $multiplier: 1 ) {
	@return calc( #{$multiplier} * ( #{( $button-border-width * 2 ) + ( $button-padding-y * 2 ) + #{$button-line-height * 1em}} ) );
}
@function button-inner-size( $multiplier: 1 ) {
	@return calc( #{$multiplier} * ( #{#{$button-padding-y * 2} + #{$button-line-height * 1em}} ) );
}

@function toolbar-button-size( $multiplier: 1 ) {
	@return calc( #{$multiplier} * ( #{($toolbar-button-border-width * 2) + ($toolbar-button-padding-y * 2) + #{$toolbar-button-line-height * 1em}} ) );
}
@function toolbar-button-inner-size( $multiplier: 1 ) {
	@return calc( #{$multiplier} * ( #{#{$toolbar-button-padding-y * 2} + #{$toolbar-button-line-height * 1em}} ) );
}
```
