### ISSUE TITLE
Incorrect styles for Selected and Locked cells

### ISSUE THREAD

**Issue by xarety** [telerik/kendo-react#372]
## I'm submitting a...
* Regression report

## Current behavior
Other grid contents shine through locked and selected cells.

## Expected behavior
Locked column obscure other content in the grid

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/selected-locked-column?file=app/main.jsx
1. Select a row
2. Scroll to the right

![image](https://user-images.githubusercontent.com/17852627/67987310-1a3eb580-fc3e-11e9-9749-04dfc00c06e8.png)

**Comment by xarety** [comment]
Also, locked cells haven't row hover color.

**Comment by xarety** [comment]
@silviyaboteva, or is it intentional?

**Comment by silviyaboteva** [comment]
Hi @xarety, 

Indeed, we reproduce both issues and they will be fixed with the next version of themes.
- The first it is due to the fact that selected rows have background color with opacity. Currently, the workaround would be to add the following css rules:

```css
.k-master-row.k-state-selected .k-grid-content-sticky {
	background-color: #ffd8d5;
}

.k-master-row.k-alt.k-state-selected .k-grid-content-sticky {
	background-color: #f8d1ce;
}
```

- The second one (with hover effect) could be fixed applying the following rule:
```css
.k-master-row:hover .k-grid-content-sticky {
	color: #656565;
  background-color: #ededed;
}
```

Demo: https://stackblitz.com/edit/selected-locked-column-8mz7rh?file=index.html 

Thank you for bringing this to our attention!
