### ISSUE TITLE
My Pdf seen to have corrupted font

### ISSUE THREAD

**Issue by vuggg** [telerik/kendo-react#426]
I'm using kendo-react-pdf to create pdf from React component. But When I used vietnamese in it My document become corrupted.

How can I fix it?

**Comment by nstoychev** [comment]
@vuggg - Please check the following article as the fonts have to be hosted on the same domain in order to be exported in the PDF:

https://www.telerik.com/kendo-react-ui/components/drawing/limitations-browser-support/#toc-cross-origin-resources

_Images that are hosted on different domains are exported only if the server provides permissive Cross-Origin HTTP headers. Similarly, fonts might not be loaded across domains. Even with the proper CORS headers, Internet Explorer 9 is not able to load images or fonts from another domain and might raise a security exception. If your application supports Internet Explorer 9, make sure that you host images and fonts on the same domain as the application._

**Comment by vuggg** [comment]
I means How can I use Vietnamese in PDF.

**Comment by nstoychev** [comment]
You need to embed a font in exported PDF document which support Unicode characters.
```css
<style>
  /*
      Use the DejaVu Sans font for displaying and embedding in the PDF file.
      The standard PDF fonts do not support Unicode characters.
  */
  div {
    font-family: "DejaVu Sans", "Arial", sans-serif;
    font-size: 12px;
  }

  /*
    The example loads the DejaVu Sans from the Kendo UI CDN.
    Other fonts have to be hosted from your application.
    The official site of the Deja Vu Fonts project is
    https://dejavu-fonts.github.io/.
  */
  @font-face {
    font-family: "DejaVu Sans";
    src: url("https://kendo.cdn.telerik.com/2017.2.621/styles/fonts/DejaVu/DejaVuSans.ttf") format("truetype");
  }

  @font-face {
    font-family: "DejaVu Sans";
    font-weight: bold;
    src: url("https://kendo.cdn.telerik.com/2017.2.621/styles/fonts/DejaVu/DejaVuSans-Bold.ttf") format("truetype");
  }

  @font-face {
    font-family: "DejaVu Sans";
    font-style: italic;
    src: url("https://kendo.cdn.telerik.com/2017.2.621/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf") format("truetype");
  }

  @font-face {
    font-family: "DejaVu Sans";
    font-weight: bold;
    font-style: italic;
    src: url("https://kendo.cdn.telerik.com/2017.2.621/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf") format("truetype");
  }
```
Here is an example - https://stackblitz.com/edit/react-p6sqxw?file=app%2Fmain.jsx. 

Additional information can be found here - https://www.telerik.com/kendo-react-ui/components/drawing/pdf-output/embedded-fonts/.
