### ISSUE TITLE
DropDownList menu is behind the Dialog

### ISSUE THREAD

**Issue by tpmh31292** [telerik/kendo-react#45]
## I'm submitting a...
* Bug report 

## Current behavior
DropDownList menu is behind the Dialog

## Expected behavior
It should be above the Dialog and not covered by the Dialog

## Minimal reproduction of the problem with instructions
https://next.plnkr.co/edit/OY5VngU7Gb6ASF89

**Comment by Xizario** [comment]
@tpmh31292, thank you for the bug report. We will fix the issue.

As a temporary solution you can resolve it by adding such CSS rule in your page.
```css
      .k-animation-container{
        z-index: 10003
      }
```
